name: Build Gradle project

on:
  issue_comment:
    types:
      - created
    branches:
      - master
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'deploy'
          reaction: rocket
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build